--- # provisioning EC2 instance
- hosts: localhost
  connection: local
  remote_user: ecuser
  become: yes
  gather_facts: no
  vars_files:
  - files/awscred.yml # need to create that folder and place credentials there. 
  tasks:
  - name: Standard povisioning of 4 t2.micro EC2 instances
    ec2: 
      aws_access_key: "{{ aws_id }}" 
      aws_secret_key: "{{ aws_key }}" 
      region: "{{ aws_region }}"
      image: ami-f0091d91
      instance_type: t2.micro
      count: 4
#lllll
